module.exports = [
  "There are two types of tragedies in life: one is not getting what you want, and the other is getting it.",
  "The key to a happy life is to accept that you are never actually in control.",
  "I believe that relationships are leverage. The more you have, the more power you have.",
  "Lies by omission are still lies, Harold. Some would argue they are the worst kind.",
  "The world is rarely fair. It is just fairer than death, that's all.",
  "In this world, there are no good men or bad men. It is just a bunch of men doing their best to get by.",
  "Revenge is not a passion. It is a disease. It eats at your mind until all you can think of is how to inflict the same pain on those who hurt you.",
  "People say money cannot buy happiness, but it can buy you a yacht big enough to sail right up to it.",
  "There is nothing that cannot be accomplished with a little ingenuity and a lot of explosives.",
  "The art of conversation lies in listening.",
  "The measure of a man is not how he behaves in moments of comfort and convenience, but how he stands in times of controversy and challenge.",
  "The past always finds a way to catch up with you. It is just a matter of when.",
  "Trust is overrated. Control is everything.",
  "The world is full of bad people, Harold. That is why good people have to work together.",
  "A friend is just an enemy in disguise.",
  "Regret is the cancer of life. It eats away at your soul until there is nothing left.",
  "Knowledge is power, my dear. But a little paranoia never hurts either.",
  "There is nothing more dangerous in this world than a man with nothing left to lose.",
  "The only way to stay ahead in this game is to have a strategy and never reveal your true intentions.",
  "The sins of the father are to be laid upon the children.",
  "In life, there are no do-overs. But there are second chances.",
  "One man's villain is another man's hero.",
  "Love is just a chemical reaction. It is not something to be taken lightly.",
  "Success is often built on a mountain of failures.",
  "Never underestimate the power of a well-timed distraction.",
  "The truth will set you free, but first it will make you angry.",
  "We all wear masks, some more than others.",
  "The road to hell is paved with good intentions.",
  "Forgiveness is a luxury not everyone can afford.",
  "We are all puppets, Harold. Some of us just have more strings than others.",
  "Money cannot buy happiness, but it can buy a damn good alibi.",
  "The line between good and evil is often blurred. It is the choices we make that define us.",
  "The greatest trick the devil ever pulled was convincing the world he did not exist.",
  "Knowledge without action is meaningless.",
  "Never trust a man who smiles too much. It is either a sign of charm or a sign of madness.",
  "There are no shortcuts in life, only detours.",
  "Greed is a bottomless pit. Once you start down that path, you can never turn back.",
  "The world is full of secrets, my dear. Some are worth dying for.",
  "Life is a game, Harold. And I always play to win.",
  "Everyone has an agenda. The trick is figuring out what it is before they figure out yours.",
  "There is no such thing as a coincidence, only hidden connections waiting to be discovered.",
  "The past is a ghost that never truly leaves us.",
  "The truth is a weapon, Harold. Wield it carefully.",
  "People only see what they want to see. It is easier that way.",
  "We are all pawns in someone else's game, my dear. The trick is to know when to make your move.",
  "The world is full of fools and idiots. It is up to us to decide which category we fall into.",
  "Power is a double-edged sword. It can build empires or destroy them.",
  "Life is all about perception. It is what you make of it that counts.",
  "There is no such thing as luck, just well-placed opportunities.",
  "In this world, loyalty is rare. That is why it is so valuable.",
  "The world is a stage, my dear, and we are all just players.",
  "The past is a prison. It is up to us to break free.",
  "Sometimes the truth hurts, but it is better than living a lie.",
  "Never let your emotions cloud your judgment. That is when mistakes are made.",
  "Control is an illusion. The sooner you realize that, the better off you will be.",
  "Life is full of surprises. Embrace them, for they are what make us human.",
  "The mind is a powerful weapon. Wield it wisely.",
  "There is a fine line between genius and madness. I prefer to dance on it.",
  "The greatest strength lies in knowing your weaknesses.",
  "Money cannot buy you happiness, but it can buy you freedom.",
  "Trust no one. Not even yourself.",
  "The only way to truly know someone is to see how they handle power.",
  "The world is a dangerous place. It is up to us to make it a little safer.",
  "Sometimes the only way to move forward is to revisit the past.",
  "The truth is a weapon, my dear. Wield it with care.",
  "Life is a game of chess, my dear. One wrong move and it is game over.",
  "There are no second chances in life, only opportunities.",
  "The world is a puzzle, my dear. It is up to us to find the missing pieces.",
  "In this world, you are either predator or prey. Choose wisely.",
  "The greatest weapon is not a gun or a knife. It is the mind.",
  "Life is all about choices. Choose wisely.",
  "The world is full of liars and deceivers. It is up to us to see through their masks.",
  "The past is a burden we all carry. It is up to us to learn from it.",
  "The truth is a dangerous thing. Handle it with care.",
  "In this world, there are no heroes or villains. Only survivors.",
  "The world is full of secrets, my dear. Some are worth dying for.",
  "Sometimes the only way to win is to play dirty.",
  "Never underestimate the power of a well-timed lie.",
  "The world is a chessboard, my dear. We are all just pawns in the game.",
  "The past is a haunting presence. It is up to us to confront our demons.",
  "The greatest weapon is not violence, but knowledge.",
  "In this world, trust is a luxury. Use it sparingly.",
  "The world is full of snakes and vipers. It is up to us to avoid their bite.",
  "The truth is a double-edged sword. It can set you free or destroy you.",
  "In this world, everyone has a price. The question is whether you are willing to pay it.",
  "Life is a puzzle, my dear. It is up to us to find the missing pieces.",
  "The past is a prison we lock ourselves in. It is up to us to find the key.",
  "Sometimes the only way to survive is to embrace the darkness within.",
  "In this world, nothing is what it seems. Trust your instincts, for they never lie.",
  "The greatest secrets are hidden in plain sight. It is up to us to uncover them.",
  "The world is a battlefield, my dear. It is up to us to fight for what we believe in.",
  "In this world, loyalty is a rare commodity. Cherish it when you find it.",
  "The past is a tapestry of mistakes and regrets. It is up to us to weave a better future.",
  "Sometimes the only way to find yourself is to lose everything.",
  "In this world, power is everything. The rest is just an illusion.",
  "The greatest weapon is not a gun or a bomb. It is the truth.",
  "The world is full of wolves and sheep. Be the wolf.",
  "In this world, there are no heroes or villains. Only survivors.",
  "The past is a ghost that never truly leaves us. It is up to us to make peace with it.",
  "Life is a game, my dear. Play it to win, or do not play at all.",
];
